### ISSUE TITLE
MaxTotalJobs and MaxWaitingJobs

### ISSUE THREAD

**Issue by marianne013** [ic-hep/GridPPDIRAC#13]
Taking onboard Simon's comment ("stick to glue, not glue2"), could we try to set
MaxTotalJobs to GlueSubClusterLogicalCPUs (or set it to GlueCEInfoTotalCPUs unless this is zero, in which case use GlueSubClusterLogicalCPUs) and MaxWaitingJobs (which currently seems to be set at 1/10th of MaxTotalJobs) to 2* MaxTotalJobs in the bdii agent.

**Comment by alexanderrichards** [comment]
Sure, I'll implement these changes
