### ISSUE TITLE
Support for vo.southgrid.ac.uk

### ISSUE THREAD

**Issue by twhyntie** [ic-hep/GridPPDIRAC#21]
Hello,

Could we add support for the SouthGrid incubator VO please? I see it's not listed in the DFC:

```bash
FC:/> cd /
FC:/> ls
cernatschool.org
comet.j-parc.jp
gridpp
lsst
lz
na62.vo.gridpp.ac.uk
pheno
snoplus.snolab.ca
t2k.org
vo.landslides.mossaic.org
vo.londongrid.ac.uk
vo.northgrid.ac.uk
```

And obviously one cannot simply `mkdir` in `/` :-)

Thanks, Tom

**Comment by marianne013** [comment]
Hi Tom,

you are the first one to ask for support for southgrid/scotgrid. I'll put it on the list, put realistically, it'll be after Christmas as I am marking all week....

Cheers,
Daniela

**Comment by twhyntie** [comment]
Hello,

Given the Ganga workshop seemed to go OK without needing SouthGrid/ScotGrid (i.e. I think everyone used `gridpp`), I'm happy to close this for now until someone specifically requests it.

Thanks again, Tom
