### ISSUE TITLE
Support for vo.scotgrid.ac.uk

### ISSUE THREAD

**Issue by twhyntie** [ic-hep/GridPPDIRAC#22]
Hello,

Could we add support for the ScotGrid incubator VO please? I see it's not listed in the DFC:

```bash
FC:/> cd /
FC:/> ls
cernatschool.org
comet.j-parc.jp
gridpp
lsst
lz
na62.vo.gridpp.ac.uk
pheno
snoplus.snolab.ca
t2k.org
vo.landslides.mossaic.org
vo.londongrid.ac.uk
vo.northgrid.ac.uk
```

Thanks, Tom

**Comment by sfayer** [comment]
Hi Tom,

Do we have users from ScotGrid and SouthGrid who actually want to test & use this? We're happy to configure it, but only want to add things that are actually going to be properly tested & then used.

Regards,
Simon

**Comment by twhyntie** [comment]
@sfayer I think the Ganga workshop on Thursday 14th Jan 2016 would be a good opportunity to test the incubator VOs - and I can think of at least one ScotGrid user (Sam S) and one SouthGrid user (Ewan M) who could do the testing. Would that be OK?

Thanks, @twhyntie

**Comment by marianne013** [comment]
Hi Tom, 

we'll have a go. But there's no pilot role in scotgrid and in southgrid Ewan still has the pilot role, which he will have to abandon first, as dirac gets touchy about users with pilot roles that aren't pilots (I'm speaking from experience).

Cheers,
Daniela

**Comment by twhyntie** [comment]
@marianne013 Brilliant, thanks - I'm happy to help coordinate this and raise the necessary GGUS tickets to get it in place for the 14th Jan. But let's leave until after Christmas :-)

Thanks again and enjoy the break! @twhyntie

**Comment by marianne013** [comment]
Hi Tom,

We've enabled scotgrid and southgrid on the dirac server, but whether there are any sites that support the pilot role and hence dirac for these VOs I don't know. Could you get the VOs to run some tests and/or get the sites to update ? 
These VOs are all sustained by grid admins, they really should know what they are doing :-P

**Comment by twhyntie** [comment]
Hello,

I'm happy to wait until someone asks for these now - using the `gridpp` VO seems to be the easiest thing for most new users at the moment, and it's what's documented in the UserGuide.

Thanks again, @twhyntie

**Comment by sfayer** [comment]
@twhyntie, can you please use the issue tracker on https://github.com/ic-hep/DIRAC for any future requests?

Regards,
Simon
