### ISSUE TITLE
[DFC CLI] id command produces an error

### ISSUE THREAD

**Issue by twhyntie** [ic-hep/GridPPDIRAC#23]
Hello,

Not a huge/urgent thing but I noticed that when in the DIRAC File Catalog Command Line Interface (CLI) the `id` command produces the following error:

```bash
$ cd $DIRAC
$ . bashrc
$ dirac-proxy-init -g gridpp_user -M
.
. [Output]
.
$ dirac-dms-filecatalog-cli
Starting FileCatalog client

File Catalog Client $Revision: 1.17 $Date: 

FC:/> id
Error: Permission denied
```
Any thoughts? I'm guessing it's harmless but thought I'd flag it up just in case.

Thanks, @twhyntie

**Comment by twhyntie** [comment]
I'm also getting the same error for `user show` and `group show`, but perhaps that's to be expected...

**Comment by marianne013** [comment]
You are right and I can only run these commands as admin.
I'm not sure you should be able to do user show as it lists *all* users (and then some, I might have to try and work out what it actually does, sigh), though I can't see what harm a summary could do.
FC:/> user show
daniela.bauer:t2k.org : 11
       daniela.bauer : 2
       thomas.morgan : 18
     frederic.brochu : 4
     t2k.org:t2k.org : 13
         simon.fayer : 1
         steve.lloyd : 17
         dirac_admin : 9
         mark.slater : 6
                   0 : 15
     alastair.currie : 16
         duncan.rand : 8
             t2k.org : 12
  alexander.richards : 20
t2k.org:t2k.org_user : 14
 ewen.lawson.gillies : 10
          tony.price : 7
       stephen.jones : 5
      samuel.skipsey : 3
         tom.whyntie : 19

The id should work, but clearly doesn't. There's probably some subtlety in the permissions Simon and me missed, as it's non trivial. We'll look into it.

**Comment by twhyntie** [comment]
Cool. You're right, the `user` and `group` commands should probably be admin only and shouldn't be listed with the `help` command when run as a non-admin :-)

**Comment by sfayer** [comment]
The "id" command uses the same code as the user and group commands internally (it gets a list of all the users and groups and searches it for the current user). There is no administrator control over these permissions, the requirement that the caller is an admin is hardcoded in... If you want it fixing I think you'd have to ask the DIRAC developers, although it'll only print the same username & group that dirac-proxy-info displays along with the (relatively meaningless) DFC UID/GID.

**Comment by twhyntie** [comment]
@sfayer Great, thanks for the info - yes, definitely one for the DIRAC devs there...

Thanks too for the `dirac-proxy-info` pointer too - that'll do what I need nicely (I didn't spot it spat out the DIRAC username along with the DN).

Issue closed, thanks both!
