### ISSUE TITLE
[Wishlist] Automatic creation of a user's home directory?

### ISSUE THREAD

**Issue by twhyntie** [ic-hep/GridPPDIRAC#24]
Hello,

Super-ultra luxury gold-plated feature request, and not urgent at all, but: given user registration by VO is automatic now (woohoo!), would it be possible to create a user directory in the VO's `user` directory? With directories organised by the first letter of the user name or surname? e.g.

```bash
/gridpp/user/w/tom.whyntie
/cernatschool.org/user/w/tom.whyntie
```

What do you think? It would be useful for new users starting out, but the hassle may not justify what could be done by the user themselves with the `mkdir` command in the DFC Command Line Interface...

Thanks, @twhyntie

**Comment by sfayer** [comment]
We think this is probably too complicated... We could make the directories based on the first letter of the username, but this then adds extra dependencies to the bdii2cs module. Different VOs may also want to do different things, so the solution wouldn't be universal. I'm not even sure that users have to make the directory explicitly themselves anyway, (as with everything griddy) uploading a file to a path that doesn't exist should create it...

Regards,
Simon

**Comment by twhyntie** [comment]
@sfayer Ah yes, the VO thing is going to be an issue - no problem, will update the UserGuide accordingly.

Thanks again, @twhyntie
