### ISSUE TITLE
[Metadata and DFC] Error with dirac-dms-find-lfns command

### ISSUE THREAD

**Issue by twhyntie** [ic-hep/GridPPDIRAC#26]
Hello,

Not a complete showstopper, but in case it's a symptom of something more fundamental...

I've been exploring the DIRAC command line tools and tried the `dirac-dms-find-lfns` command, which finds file LFNs by user metadata set in the DFC.

I can successfully set the metadata using the DFC Command Line Interface (CLI) (i.e. what you get with `dirac-dms-filecatalog-cli`), and use that metadata to find files via the DIRAC Python API (which is great!). But the `dirac-dms-find-lfns` command doesn't appear to work:

```bash
$ dirac-dms-find-lfns Path=/cernatschool.org/data "experiment=MoEDAL"
Can not access File Catalog: Failed to perform getMetadataFields from any catalog
```

Like I say, we'd actually want to use the Python API to access the files via the metadata, so if it's not something obvious/trivial don't worry about it, but for completeness/symmetry it might be nice to be able to use metadata-based functionality with all three (DFC CLI, command line tools, and the Python API) methods...

Thanks as ever, @twhyntie

**Comment by sfayer** [comment]
Hi,

The method the command-line client uses to do this query seems to rely on a new(ish) parameter called "MetaCatalog" to pick the catalog(s) to query; we didn't have this set. I've added this and the example command you included now returns a set of results.

Regards,
Simon

**Comment by twhyntie** [comment]
Yup, perfect - works for me too! Glad it was a simple fix, many thanks for investigating. @twhyntie
