### ISSUE TITLE
[Multi VO] Trying to retrieve files from a differet VO throws a misleading error

### ISSUE THREAD

**Issue by twhyntie** [ic-hep/GridPPDIRAC#28]
Here's fun!

`/gridpp/userguide/WELCOME.md` was uploaded with a `-g gridpp_user` proxy. Trying to download with a different VO proxy (e.g. `-g cernatschool.org_user`) fails - _as it should_ - but with the wrong error.

```bash
$ dirac-dms-get-file /gridpp/userguide/WELCOME.md
Failures occurred during rm.getFile 
{'Failed': {'/gridpp/userguide/WELCOME.md': 'Failed to get local copy from any replicas\nError getting file from storage: /gridpp/userguide/WELCOME.md from UKI-LT2-QMUL2-disk, LFN does not follow the DIRAC naming convention /gridpp/userguide/WELCOME.md'},
 'Successful': {}}
ERROR {'Successful': {}, 'Failed': {'/gridpp/userguide/WELCOME.md': 'Failed to get local copy from any replicas\nError getting file from storage: /gridpp/userguide/WELCOME.md from UKI-LT2-QMUL2-disk, LFN does not follow the DIRAC naming convention /gridpp/userguide/WELCOME.md'}}
```

I'm guessing this is one to take to the DIRAC devs but thought I'd flag it up here first - what do you think?

Thanks as ever, @twhyntie

**Comment by sfayer** [comment]
Well, the error message is technically correct; the LFN specified doesn't follow the /\<users_voname\>/... convention. If you would like the error to be more clear then, yes, you should probably ask the developers. (My suggestion would be for this to print what it was expecting, which should make the mistake more obvious).

Regards,
Simon

**Comment by twhyntie** [comment]
Ahhhhh... I see, thanks for the clarification. Your suggestion is a good one - I'll submit an issue there.

Thanks again, @twhyntie
