### ISSUE TITLE
Supress proxy expiry warnings for short proxies

### ISSUE THREAD

**Issue by sfayer** [ic-hep/GridPPDIRAC#75]
The DIRAC expired proxy warning e-mails are sent even if the originally uploaded proxy was less than 1 month to start off with (i.e. they start getting sent immediately in that case); this is annoying.

It would be good to add a new configuration option that sets a minimum lifetime threshold for these notices. If an uploaded proxy's original lifetime (i.e. expiry_time - upload_time (or start_time)) is not above this threshold then the warning e-mails should never be sent.

This should be implemented in vanilla DIRAC and sent as a pull request upstream.

**Comment by sfayer** [comment]
This one may still be a problem and we should look at it. The database doesn't have the start time field, but it should be possible to extract it by decoding the PEM string.

**Comment by marianne013** [comment]
Wasn't this only caused by DUNE and their silly autogenerated certs ? If so, we can  probably close and ignore as for everyone else it's OK.

**Comment by sfayer** [comment]
Yes, it was mostly DUNE people, but in a "token to proxy" translation world, it'll re-appear, so decided to keep it open.
I would hope it's only a simple fix (without actually looking at the code), something like:
```python
if (expiry_date - decode_pem(pem).start_date) < IGNORE_TIME: continue
```

**Comment by marianne013** [comment]
Maybe that should go upstream as well then ?

**Comment by sfayer** [comment]
Yes, probably. Possibly ask about it at a BiLD meeting?

**Comment by marianne013** [comment]
My list is increasing :-)

**Comment by marianne013** [comment]
Well, apparently it will come up when the tokens come in, but then hopefully upstream will fix it. I don't think DUNE is going to make a come back on our DIRAC server,
