### ISSUE TITLE
Only set MaxProcessors if it's not already set

### ISSUE THREAD

**Issue by marianne013** [ic-hep/GridPPDIRAC#76]
We need to be able to set e.g. RAL by hand.

**Comment by sfayer** [comment]
Yet another one where no-one is complaining: I think we may have a hack in for this that just hardcodes a few values for RAL. Setting it if it isn't already set wouldn't allow us to change the default, which we have done in the past.

**Comment by marianne013** [comment]
We currently set it to 64 everywhere, I think we gave up on anything more precise. If it's not done yet, it would be good to have this defined as a constant in one place, so we can find it easily.
