### ISSUE TITLE
GPU details to CS Agent

### ISSUE THREAD

**Issue by sfayer** [ic-hep/GridPPDIRAC#79]
Hi Alex,

We would like a new Agent writing to import GPU information into the DIRAC CS from GOCDB (GPU2CSAgent?). The algorithm should be something like:

 * Loop over all CEs (including VAC & Vcycle ones) in the CS.
 * For each CE get the extension parameters for the CE from GOCDB (just like we did for the VAC sites).
 * Look for entries in the form GPU_GridPP[_queue] with value \<Software\>_\<Memory\>[_EX] (note that queue may itself contain underscores). The name should be case insensitive except for the _queue bit.
 * For tags without a queue name suffixed, set tags for all queues for the CEs.
 * For tags with a queue, set only the tags for that queue, if it exists (otherwise ignore it)... Queue specific tags should override tags from the previous rule (as they are more specific).

 * The fields which should be created in the CS are Tag, RequiredTag and GPULastSeen.
 * GPULastSeen should be updated, just like the LastSeen of various other agents.
 * Tag and RequiredTag are lists.
 * \<Software\> must be CUDA or OpenGL (case insensitive when matching from GOCDB, but converted to the proper format for the tags).
 * \<Memory\> must be an integer \>= 0.
 * If either \<Software\> or \<Memory\> contain an invalid field, a warning should be generated and the entry should be skipped.
 * _EX should also be case insensitive.
 * The following Tag values should be created: "\<Software\>", "GPU". If _EX was specified, also add "GPUExclusive", otherwise "GPUNonExclusive". For each value of memory from 0 to \<Memory\>, "GPUXGB". For example if \<Memory\> is 2, GPU0GB, GPU1GB and GPU2GB should be created.
 * RequiredTag should be set to a list containing a single value, GPU.

 * At the end, any entries where the GPULastSeen is more than a configurable time old (say 3 days), should have all GPU specific tags removed (all tags & required tags starting with "GPU"). If the Tag & RequiredTag fields then don't contain anything any more, they should be deleted entirely; GPULastSeen should also be deleted when this process happens.
 * Edge case: If a queue specific tag GPU_GridPP_queue is deleted and GPU_GridPP exists, then the tags should all revert back to those values.

In a extension name the "_GridPP" bit should also be configurable, just like it was for the Vac2CS agent.

Regards,
Simon

**Comment by fstagni** [comment]
There's a GOCDB2CSAgent in vanilla DIRAC, please use/modify that one.

**Comment by sfayer** [comment]
I think I'll close this for now... We'll have to work out exactly how we want to support GPUs when we have users that actually want to use them beyond basic tests.
