### ISSUE TITLE
InputSandbox = {"solid.sh";} (as opposed to {"solid.sh"}; ) should not kill the Optimizer

### ISSUE THREAD

**Issue by marianne013** [ic-hep/GridPPDIRAC#80]
At the moment, a hapless typo (as above) crashes the Optimizers, which tried to restart and process the same faulty jdl (and no others) again. This can only be fixed by editing the database by hand.

**Comment by sfayer** [comment]
We've not found a way to fix this and it hasn't really happened again. If anything, it should be re-opened as an upstream ticket.

**Comment by marianne013** [comment]
Let me run a test and if  it happens again I can file an upstream issue.

**Comment by marianne013** [comment]
I've just submitted a job with the following JDL:
```
[
Executable = {"diractest.sh";}
Arguments = "testarg1 testarg2";
StdOutput = "job.log";
StdError = "job.log";
InputSandbox = "diractest.sh";
OutputSandbox = "job.log";
Site = "LCG.UKI-LT2-IC-HEP.uk";
JobName = "DiracTest";
Platform = "AnyPlatform";

]
```
(1099 on dirac00).
The auto generated JDL in DIRAC looks like this:
```
[
  OwnerGroup = "lz_user";
  DIRACSetup = "GridPP";
  VirtualOrganization = "lz";
  Priority = 1;
  CPUTime = 86400;
  JobID = 1099;
  OwnerDN = "/C=UK/O=eScience/OU=Imperial/L=Physics/CN=daniela bauer";
  JobRequirements =
  [
    OwnerDN = "/C=UK/O=eScience/OU=Imperial/L=Physics/CN=daniela bauer";
    VirtualOrganization = "lz";
    Setup = "GridPP";
    CPUTime = 86400;
    OwnerGroup = "lz_user";
    UserPriority = 1;
    Platforms = "EL7";
  ];
  OwnerName = "daniela.bauer";
  Owner = "daniela.bauer";
  Platform = "EL7";
]
``` 
(note how the site and executable have disappeared). As it's LZ it tends to end up on the cloud where it fails with:
"Exception During Execution".
It doesn't seem to kill the Optimizer, a later submitted job with a correct JDL work fine, so there must have been something else that JDL to trigger that bug. 
Propose to close.

**Comment by sfayer** [comment]
It was probably fixed upstream already then. I've already closed the ticket.
